customer: platform
vertical: cdc
multistage: true
services:
- id: consumerexample
  type: dockerfile
  scale: single
  resources:
    requests:
      memory: 180Mi
      cpu: 8m
    limits:
      memory: 400Mi
      cpu: 1000m
  check: true
tests:
- stage: pp
  test: chmod +x scripts/tests.sh && sh ./scripts/tests.sh
  type: dockerfile
watchers:
- uwe.daub@metronom.com 
slack-channels:
- '@peng-cdc'
