apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaconsumer
spec:
  replicas: 2
  selector:
    matchLabels:
      service: javaconsumer
  template:
    metadata:
      labels:
        service: javaconsumer
    spec:
      containers:
      - name: javaconsumer
        image: __DOCKER_IMAGE__
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
