apiVersion: v1
kind: Service
metadata:
  name: javaconsumer
  labels:
    service: javaconsumer
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30036
      targetPort: 8080
      name: http
  selector:
    service: javaconsumer